# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and push
        run: npm install
      - run: npm run docs:build
      - run: cd docs/.vuepress/dist
      - run: git init
      - run: git add -A
      - run: git config --global user.email "372354984@qq.com"
      - run: git config --global user.name "dealloc"
      - run: git commit -m 'deploy'
      - run: git push -f https://github.com/372354984/dealloc.co.git docs
